openapi: "3.0.0"
info:
  description: "Please add descriptionFirst proposal for a Restfull API with a data\
    \ model inspired by https://github.com/Boavizta/PCR-SI_dataformat/ .\n\n    Only\
    \ a Simple CRUD on Report is specified\n    Post is use to post a report request\
    \ with the inventory and electricy / energy mix and should reply an http status\
    \ code 202 with URI of future report\n    Get is use to retrieve a specific report\
    \ with its ID\n    Find is use de find a report with some criterias\n\nSwagger\
    \ is here\nAnd in a live SwaggerUI\n\nSub Resource management may be designing\n\
    \ndata model discordance\n\nRestFull API require same model for request & responses.\
    \ A first proposal is bassed on report resource which hold request.json essentilas\
    \ attribute\n\nanother strategy is to post a report_request item which generate\
    \ a report item"
  version: "0.1.0_inProgress"
  title: "Proposal"
tags:
- name: "Report"
paths:
  /report:
    get:
      tags:
      - "Report"
      operationId: "reportFind"
      summary: "find report"
      parameters:
      - name: "organisation"
        required: false
        in: "query"
        schema:
          type: "string"
      - name: "provider"
        required: false
        in: "query"
        schema:
          type: "string"
      responses:
        "200":
          description: "Ok"
          content:
            application/json;charset=utf-8:
              schema:
                type: "array"
                items:
                  $ref: "#/components/schemas/Report"
        "400":
          description: "Bad Request\n\n"
          content:
            application/json;charset=utf-8:
              schema:
                $ref: "#/components/schemas/"
        "404":
          description: "Not Found\n\n"
          content:
            application/json;charset=utf-8:
              schema:
                $ref: "#/components/schemas/"
        "405":
          description: "Method Not Allowed\n\n"
          content:
            application/json;charset=utf-8:
              schema:
                $ref: "#/components/schemas/"
        "422":
          description: "Unprocessable entity\n\n"
          content:
            application/json;charset=utf-8:
              schema:
                $ref: "#/components/schemas/"
        "500":
          description: "Internal Server Error\n\n"
          content:
            application/json;charset=utf-8:
              schema:
                $ref: "#/components/schemas/"
        "503":
          description: "Service Unavailable\n\n"
          content:
            application/json;charset=utf-8:
              schema:
                $ref: "#/components/schemas/"
    post:
      tags:
      - "Report"
      operationId: "reportCreate"
      summary: "create report"
      requestBody:
        required: true
        content:
          application/json;charset=utf-8:
            schema:
              $ref: "#/components/schemas/Report"
      responses:
        "202":
          description: "Accepted"
        "400":
          description: "Bad Request\n\n"
          content:
            application/json;charset=utf-8:
              schema:
                $ref: "#/components/schemas/"
        "404":
          description: "Not Found\n\n"
          content:
            application/json;charset=utf-8:
              schema:
                $ref: "#/components/schemas/"
        "405":
          description: "Method Not Allowed\n\n"
          content:
            application/json;charset=utf-8:
              schema:
                $ref: "#/components/schemas/"
        "422":
          description: "Unprocessable entity\n\n"
          content:
            application/json;charset=utf-8:
              schema:
                $ref: "#/components/schemas/"
        "500":
          description: "Internal Server Error\n\n"
          content:
            application/json;charset=utf-8:
              schema:
                $ref: "#/components/schemas/"
        "503":
          description: "Service Unavailable\n\n"
          content:
            application/json;charset=utf-8:
              schema:
                $ref: "#/components/schemas/"
  /report/{reportId}:
    get:
      tags:
      - "Report"
      operationId: "reportGet"
      summary: "get report"
      parameters:
      - name: "reportId"
        required: true
        in: "path"
        schema:
          type: "string"
      responses:
        "200":
          description: "Ok"
          content:
            application/json;charset=utf-8:
              schema:
                $ref: "#/components/schemas/Report"
        "400":
          description: "Bad Request\n\n"
          content:
            application/json;charset=utf-8:
              schema:
                $ref: "#/components/schemas/"
        "404":
          description: "Not Found\n\n"
          content:
            application/json;charset=utf-8:
              schema:
                $ref: "#/components/schemas/"
        "405":
          description: "Method Not Allowed\n\n"
          content:
            application/json;charset=utf-8:
              schema:
                $ref: "#/components/schemas/"
        "422":
          description: "Unprocessable entity\n\n"
          content:
            application/json;charset=utf-8:
              schema:
                $ref: "#/components/schemas/"
        "500":
          description: "Internal Server Error\n\n"
          content:
            application/json;charset=utf-8:
              schema:
                $ref: "#/components/schemas/"
        "503":
          description: "Service Unavailable\n\n"
          content:
            application/json;charset=utf-8:
              schema:
                $ref: "#/components/schemas/"
    delete:
      tags:
      - "Report"
      operationId: "reportDelete"
      summary: "delete report"
      parameters:
      - name: "reportId"
        required: true
        in: "path"
        schema:
          type: "string"
      responses:
        "204":
          description: "No Content"
        "400":
          description: "Bad Request\n\n"
          content:
            application/json;charset=utf-8:
              schema:
                $ref: "#/components/schemas/"
        "404":
          description: "Not Found\n\n"
          content:
            application/json;charset=utf-8:
              schema:
                $ref: "#/components/schemas/"
        "405":
          description: "Method Not Allowed\n\n"
          content:
            application/json;charset=utf-8:
              schema:
                $ref: "#/components/schemas/"
        "422":
          description: "Unprocessable entity\n\n"
          content:
            application/json;charset=utf-8:
              schema:
                $ref: "#/components/schemas/"
        "500":
          description: "Internal Server Error\n\n"
          content:
            application/json;charset=utf-8:
              schema:
                $ref: "#/components/schemas/"
        "503":
          description: "Service Unavailable\n\n"
          content:
            application/json;charset=utf-8:
              schema:
                $ref: "#/components/schemas/"
servers:
- url: "/v1"
components:
  schemas:
    EQUIPEMENT_TYPE:
      type: "string"
      enum:
      - "LAPTOP"
      - "NOT IT"
      - "SERVER"
      - "VIRTUAL MACHINE"
    Electricity_Mix:
      required:
      - "name"
      - "impact"
      - "source"
      type: "object"
      properties:
        name:
          type: "string"
        impact:
          $ref: "#/components/schemas/Impact"
        source:
          $ref: "#/components/schemas/Source"
    Impact:
      required:
      - "build"
      - "distribution"
      - "use"
      - "endOfLife"
      type: "object"
      properties:
        build:
          $ref: "#/components/schemas/Impacts_By_Indicators"
        distribution:
          $ref: "#/components/schemas/Impacts_By_Indicators"
        use:
          $ref: "#/components/schemas/Impacts_By_Indicators"
        endOfLife:
          $ref: "#/components/schemas/Impacts_By_Indicators"
    Impact_Detail:
      required:
      - "equipement_type"
      - "equipement_name"
      - "tags"
      - "quality"
      - "impact"
      - "source"
      - "provider"
      type: "object"
      properties:
        equipement_type:
          $ref: "#/components/schemas/EQUIPEMENT_TYPE"
        equipement_name:
          type: "string"
        tags:
          type: "string"
        quality:
          $ref: "#/components/schemas/Quality"
        impact:
          $ref: "#/components/schemas/Impact"
        source:
          type: "string"
        provider:
          type: "string"
    Impacts_By_Indicators:
      type: "object"
      properties:
        AP:
          type: "string"
        GWP:
          type: "string"
        CTUe:
          type: "string"
        Epf:
          type: "string"
        Epm:
          type: "string"
        Ept:
          type: "string"
        CTUh-c:
          type: "string"
        CTUh-nc:
          type: "string"
        IR:
          type: "string"
        LU:
          type: "string"
        MIPS:
          type: "string"
        ODP:
          type: "string"
        PM:
          type: "string"
        POCP:
          type: "string"
        ADPf:
          type: "string"
        ADPe:
          type: "string"
        TPE:
          type: "string"
        WU:
          type: "string"
    Inventory:
      required:
      - "equipement_type"
      - "equipement_name"
      - "quantity"
      - "unit"
      - "lifetime"
      - "quality"
      - "yearly_electricity_consupmtion_in_kwh"
      - "electricity_Mix"
      - "impacts"
      type: "object"
      properties:
        equipement_type:
          $ref: "#/components/schemas/EQUIPEMENT_TYPE"
        equipement_name:
          type: "string"
        quantity:
          type: "number"
          format: "float"
        unit:
          type: "string"
        lifetime:
          type: "number"
          format: "float"
        quality:
          $ref: "#/components/schemas/Quality"
        yearly_electricity_consupmtion_in_kwh:
          type: "number"
          format: "float"
        electricity_Mix:
          type: "string"
        tag:
          type: "string"
        impacts:
          $ref: "#/components/schemas/Impact"
    Metadata:
      required:
      - "organization"
      - "dataset"
      - "timestamp"
      - "provider"
      - "version"
      type: "object"
      properties:
        organization:
          type: "string"
        dataset:
          type: "string"
        timestamp:
          type: "string"
        provider:
          type: "string"
        sources:
          type: "array"
          items:
            $ref: "#/components/schemas/Source"
        version:
          type: "string"
    Quality:
      type: "string"
      enum:
      - "HIGH"
      - "LOW"
      - "MEDIUM"
    Report:
      type: "object"
      properties:
        metadata:
          $ref: "#/components/schemas/Metadata"
        total_impact:
          $ref: "#/components/schemas/Impact"
        tags:
          type: "array"
          items:
            $ref: "#/components/schemas/Tag"
        inventory:
          type: "array"
          items:
            $ref: "#/components/schemas/Inventory"
        quality:
          $ref: "#/components/schemas/Report_Quality"
        detailed_impact:
          type: "array"
          items:
            $ref: "#/components/schemas/Impact_Detail"
        electricity_mix:
          type: "array"
          items:
            $ref: "#/components/schemas/Electricity_Mix"
    Report_Quality:
      required:
      - "high"
      - "medium"
      - "low"
      type: "object"
      properties:
        high:
          type: "number"
          format: "float"
        medium:
          type: "number"
          format: "float"
        low:
          type: "number"
          format: "float"
    Source:
      required:
      - "name"
      - "version"
      type: "object"
      properties:
        name:
          type: "string"
        version:
          type: "string"
        href:
          type: "string"
          format: "uri"
    Tag:
      required:
      - "impacts"
      type: "object"
      properties:
        name:
          type: "string"
        impacts:
          $ref: "#/components/schemas/Impacts_By_Indicators"
